### ISSUE TITLE
Shell.js fails to judge 360se and 360ee

### ISSUE THREAD

**Issue by alansalexer** [cloudcome/alien#1]
It used to be able to distinguish 360se and 360ee before but doesn't now.

Any chance to look into this? 

Also I'm quite interested in how you know these hacks. Do you print all the Objects and compare them one by one?

**Comment by mxm145** [comment]
查看了ua跟chrome一模一样了，不知道还有没有其他办法

**Comment by cloudcome** [comment]
shell.js 会尽快更新，感谢反馈。
