### ISSUE TITLE
shell.js 新版本 360极速浏览器  偵測失敗

### ISSUE THREAD

**Issue by yesseecity** [cloudcome/alien#2]
360极速浏览器
版本号: 8.2.0.188

內核版本号: 39.0.2171.99

這個版本的360新增了 window.clientInformation.languages，之前的版本沒有。

因此這個方法會判別錯誤。

另外， Chrome 36.0   版本，因為沒有 window.clientInformation.languages ，所以會誤判成 360浏览器

**Comment by cloudcome** [comment]
感谢反馈。
