### ISSUE TITLE
shell.js 还是360浏览器的问题，会有误把chrome认为是360的情况

### ISSUE THREAD

**Issue by nonjene** [cloudcome/alien#4]
// chrome
        if (win.clientInformation && win.clientInformation.languages && win.clientInformation.languages.length > 2) {
            return 'chrome';
        }
貌似国内某些渠道下载的chrome，也是只有两个语言，不清楚具体渠道来源，只是从现有安装的判断出来，版本是44.xxx的。
这种情况会把chrome误判定是360

**Comment by nonjene** [comment]
发现clientInformation.permissions在360是不支持的，可以用这个判断

**Comment by cloudcome** [comment]
感谢反馈。目前该文件的更新程度不是很频繁，使用频度不高。
